package dev.pokepad.block

/**
 * ROLI BLOCKS protocol core — a byte-exact Kotlin port of the proven
 * Python implementation (vendored blocksd). Every code path here is held
 * to golden vectors generated by that stack (see GoldenTest): if the
 * tests pass, this speaks bit-identical ROLI.
 *
 * Ported pieces: 7-bit LSB-first packing, payload checksum, host packet
 * builder, SharedDataChange diff encoder (skip/sequence/run-length with
 * coalescing), and an instant-ack heap streamer equivalent to
 * remote_heap.send_changes.
 */
object Protocol {
    val SYSEX_HEADER = byteArrayOf(0xF0.toByte(), 0x00, 0x21, 0x10, 0x77)
    const val MAX_PACKET_BYTES = 194
    const val HEAP_SIZE = 7200

    // BitSize
    const val MESSAGE_TYPE = 7
    const val DEVICE_COMMAND = 9
    const val PACKET_INDEX = 16
    const val DATA_CHANGE_COMMAND = 3
    const val BYTE_COUNT_FEW = 4
    const val BYTE_COUNT_MANY = 8
    const val BYTE_VALUE = 8
    const val BYTE_SEQ_CONTINUES = 1

    // MessageFromHost
    const val MSG_DEVICE_COMMAND = 0x01
    const val MSG_SHARED_DATA_CHANGE = 0x02

    // DeviceCommand
    const val CMD_BEGIN_API = 0x00
    const val CMD_REQUEST_TOPOLOGY = 0x01
    const val CMD_END_API = 0x02
    const val CMD_PING = 0x03

    // DataChangeCommand
    const val DC_END_OF_PACKET = 0
    const val DC_END_OF_CHANGES = 1
    const val DC_SKIP_FEW = 2
    const val DC_SKIP_MANY = 3
    const val DC_SET_SEQUENCE = 4
    const val DC_SET_FEW = 5
    const val DC_SET_FEW_LAST = 6
    const val DC_SET_MANY = 7

    const val FEW_MAX = 15
    const val MANY_MAX = 255
    const val COALESCE_THRESHOLD = 32
    const val MIN_RUN_LENGTH = 3

    fun checksum(payload: ByteArray): Int {
        var cs = payload.size and 0xFF
        for (b in payload) cs = (cs + (cs * 2 + (b.toInt() and 0xFF))) and 0xFF
        return cs and 0x7F
    }
}

/** 7-bit-per-byte LSB-first bit packer (Packed7BitWriter port). */
class BitWriter(private val capacity: Int = 256) {
    private val data = ByteArray(capacity)
    private var bytesWritten = 0
    private var bitsInCurrent = 0

    fun writeBits(value: Int, numBits: Int) {
        var v = value
        var bits = numBits
        while (bits > 0) {
            val avail = 7 - bitsInCurrent
            val toWrite = minOf(avail, bits)
            val mask = (1 shl toWrite) - 1
            data[bytesWritten] = (data[bytesWritten].toInt() or
                    ((v and mask) shl bitsInCurrent)).toByte()
            v = v ushr toWrite
            bits -= toWrite
            bitsInCurrent += toWrite
            if (bitsInCurrent >= 7) {
                bitsInCurrent = 0
                bytesWritten++
            }
        }
    }

    fun writeBitsLong(value: Long, numBits: Int) {
        // for 32-bit fields; splits into two writes to stay in Int math
        writeBits((value and 0xFFFF).toInt(), minOf(16, numBits))
        if (numBits > 16) writeBits(((value ushr 16) and 0xFFFF).toInt(), numBits - 16)
    }

    fun hasCapacity(bitsNeeded: Int): Boolean {
        val totalBits = (bytesWritten + 2) * 7 + bitsInCurrent + bitsNeeded
        return totalBits <= capacity * 7
    }

    val size: Int get() = bytesWritten + if (bitsInCurrent > 0) 1 else 0

    fun getData(): ByteArray = data.copyOf(size)
}

/** 7-bit LSB-first reader (Packed7BitReader port). */
class BitReader(private val data: ByteArray, private val from: Int = 0,
                private val to: Int = data.size) {
    private var pos = from
    private var bitOffset = 0

    fun readBits(numBits: Int): Int {
        var value = 0
        var bitsRead = 0
        var bits = numBits
        while (bits > 0) {
            if (pos >= to) break
            val avail = 7 - bitOffset
            val toRead = minOf(avail, bits)
            val mask = (1 shl toRead) - 1
            value = value or ((((data[pos].toInt() and 0xFF) shr bitOffset) and mask) shl bitsRead)
            bitsRead += toRead
            bits -= toRead
            bitOffset += toRead
            if (bitOffset >= 7) { bitOffset = 0; pos++ }
        }
        return value
    }
}

/** HostPacketBuilder port: header + payload writer + checksum framing. */
class PacketBuilder(maxBytes: Int = 64) {
    val writer = BitWriter(maxBytes)
    private var header = ByteArray(0)

    fun sysexHeader(deviceIndex: Int) {
        header = Protocol.SYSEX_HEADER + byteArrayOf((deviceIndex and 0x3F).toByte())
    }

    fun deviceCommand(command: Int) {
        writer.writeBits(Protocol.MSG_DEVICE_COMMAND, Protocol.MESSAGE_TYPE)
        writer.writeBits(command, Protocol.DEVICE_COMMAND)
    }

    fun beginDataChanges(packetIndex: Int) {
        writer.writeBits(Protocol.MSG_SHARED_DATA_CHANGE, Protocol.MESSAGE_TYPE)
        writer.writeBits(packetIndex, Protocol.PACKET_INDEX)
    }

    fun build(): ByteArray {
        val payload = writer.getData()
        return header + payload +
                byteArrayOf(Protocol.checksum(payload).toByte(), 0xF7.toByte())
    }

    companion object {
        fun command(deviceIndex: Int, cmd: Int): ByteArray {
            val b = PacketBuilder()
            b.sysexHeader(deviceIndex)
            b.deviceCommand(cmd)
            return b.build()
        }
        fun ping(idx: Int) = command(idx, Protocol.CMD_PING)
        fun beginApi(idx: Int) = command(idx, Protocol.CMD_BEGIN_API)
        fun endApi(idx: Int) = command(idx, Protocol.CMD_END_API)
        fun requestTopology(idx: Int) = command(idx, Protocol.CMD_REQUEST_TOPOLOGY)
    }
}

/** DataChangeEncoder port: skip / sequence / run-length commands. */
class DataChangeEncoder(private val w: BitWriter) {
    var lastValue: Int? = null
        private set

    private fun cmd(c: Int) = w.writeBits(c, Protocol.DATA_CHANGE_COMMAND)

    fun skipBytes(countIn: Int) {
        var count = countIn
        while (count > 0) {
            if (count > Protocol.FEW_MAX) {
                val chunk = minOf(count, Protocol.MANY_MAX)
                cmd(Protocol.DC_SKIP_MANY)
                w.writeBits(chunk, Protocol.BYTE_COUNT_MANY)
                count -= chunk
            } else {
                cmd(Protocol.DC_SKIP_FEW)
                w.writeBits(count, Protocol.BYTE_COUNT_FEW)
                count = 0
            }
        }
    }

    fun setSequence(values: ByteArray, from: Int, len: Int) {
        if (len <= 0) return
        cmd(Protocol.DC_SET_SEQUENCE)
        for (i in 0 until len) {
            val v = values[from + i].toInt() and 0xFF
            w.writeBits(v, Protocol.BYTE_VALUE)
            w.writeBits(if (i < len - 1) 1 else 0, Protocol.BYTE_SEQ_CONTINUES)
            lastValue = v
        }
    }

    fun setRepeated(value: Int, countIn: Int) {
        var count = countIn
        while (count > 0) {
            if (count > Protocol.FEW_MAX) {
                val chunk = minOf(count, Protocol.MANY_MAX)
                cmd(Protocol.DC_SET_MANY)
                w.writeBits(chunk, Protocol.BYTE_COUNT_MANY)
                w.writeBits(value, Protocol.BYTE_VALUE)
                count -= chunk
            } else if (lastValue != null && value == lastValue) {
                cmd(Protocol.DC_SET_FEW_LAST)
                w.writeBits(count, Protocol.BYTE_COUNT_FEW)
                count = 0
            } else {
                cmd(Protocol.DC_SET_FEW)
                w.writeBits(count, Protocol.BYTE_COUNT_FEW)
                w.writeBits(value, Protocol.BYTE_VALUE)
                count = 0
            }
        }
        lastValue = value
    }

    fun end(isLast: Boolean) =
        cmd(if (isLast) Protocol.DC_END_OF_CHANGES else Protocol.DC_END_OF_PACKET)
}

data class DiffRegion(val isSkip: Boolean, var offset: Int, var count: Int)

object HeapDiff {
    fun computeDiff(current: ByteArray, target: ByteArray): MutableList<DiffRegion> {
        val size = target.size
        val regions = mutableListOf<DiffRegion>()
        var i = 0
        while (i < size) {
            val start = i
            if (current[i] == target[i]) {
                while (i < size && current[i] == target[i]) i++
                regions.add(DiffRegion(true, start, i - start))
            } else {
                while (i < size && current[i] != target[i]) i++
                regions.add(DiffRegion(false, start, i - start))
            }
        }
        coalesce(regions)
        if (regions.isNotEmpty() && regions.last().isSkip) regions.removeAt(regions.size - 1)
        return regions
    }

    private fun coalesce(regions: MutableList<DiffRegion>) {
        var i = regions.size - 1
        while (i > 1) {
            val right = regions[i]
            val skip = regions[i - 1]
            val left = regions[i - 2]
            if (!right.isSkip && skip.isSkip && !left.isSkip) {
                val total = left.count + skip.count + right.count
                if (total < Protocol.COALESCE_THRESHOLD) {
                    left.count = total
                    regions.removeAt(i)
                    regions.removeAt(i - 1)
                    i -= 2
                    continue
                }
            }
            i--
        }
    }

    private const val END_BITS = Protocol.DATA_CHANGE_COMMAND
    private const val SEQ_BASE = Protocol.DATA_CHANGE_COMMAND
    private const val SEQ_BYTE = Protocol.BYTE_VALUE + Protocol.BYTE_SEQ_CONTINUES
    private const val FEW_BITS =
        Protocol.DATA_CHANGE_COMMAND + Protocol.BYTE_COUNT_FEW + Protocol.BYTE_VALUE
    private const val FEW_LAST_BITS = Protocol.DATA_CHANGE_COMMAND + Protocol.BYTE_COUNT_FEW
    private const val MANY_BITS =
        Protocol.DATA_CHANGE_COMMAND + Protocol.BYTE_COUNT_MANY + Protocol.BYTE_VALUE

    /** encode_regions_limited port. Returns true if everything fit. */
    fun encodeLimited(
        enc: DataChangeEncoder, w: BitWriter,
        regions: List<DiffRegion>, target: ByteArray, resultState: ByteArray,
    ): Boolean {
        for (region in regions) {
            if (region.isSkip) {
                enc.skipBytes(region.count)
                continue
            }
            val encoded = encodeSetLimited(enc, w, target, resultState,
                region.offset, region.count)
            if (encoded < region.count) return false
        }
        return true
    }

    private fun encodeSetLimited(
        enc: DataChangeEncoder, w: BitWriter,
        target: ByteArray, resultState: ByteArray, offset: Int, count: Int,
    ): Int {
        var i = 0
        while (i < count) {
            var runLen = 1
            while (i + runLen < count &&
                target[offset + i + runLen] == target[offset + i]) runLen++
            val remaining = count - i
            if (runLen >= Protocol.MIN_RUN_LENGTH || remaining <= Protocol.MIN_RUN_LENGTH) {
                val v = target[offset + i].toInt() and 0xFF
                val chunk = maxRepeatedChunk(enc, w, v, runLen)
                if (chunk == 0) break
                enc.setRepeated(v, chunk)
                System.arraycopy(target, offset + i, resultState, offset + i, chunk)
                i += chunk
                continue
            }
            var j = i + 1
            while (j < count) {
                if (j + 2 < count && target[offset + j] == target[offset + j + 1] &&
                    target[offset + j] == target[offset + j + 2]) break
                j++
            }
            val chunk = maxSequenceChunk(w, j - i)
            if (chunk == 0) break
            enc.setSequence(target, offset + i, chunk)
            System.arraycopy(target, offset + i, resultState, offset + i, chunk)
            i += chunk
        }
        return i
    }

    private fun maxRepeatedChunk(enc: DataChangeEncoder, w: BitWriter,
                                 value: Int, count: Int): Int {
        if (count > Protocol.FEW_MAX && w.hasCapacity(MANY_BITS + END_BITS))
            return minOf(count, Protocol.MANY_MAX)
        if (value == enc.lastValue && w.hasCapacity(FEW_LAST_BITS + END_BITS))
            return minOf(count, Protocol.FEW_MAX)
        if (w.hasCapacity(FEW_BITS + END_BITS))
            return minOf(count, Protocol.FEW_MAX)
        return 0
    }

    private fun maxSequenceChunk(w: BitWriter, count: Int): Int {
        var low = 0
        var high = count
        while (low < high) {
            val mid = (low + high + 1) / 2
            if (w.hasCapacity(SEQ_BASE + mid * SEQ_BYTE + END_BITS)) low = mid
            else high = mid - 1
        }
        return low
    }
}

/**
 * Instant-ack heap streamer — remote_heap.send_changes equivalent for a
 * host that tracks its own confirmed state (we diff frame-to-frame and
 * seed the packet counter from observed device ACKs).
 */
class HeapStreamer(private val deviceIndex: Int, startIndex: Int) {
    val deviceState = ByteArray(Protocol.HEAP_SIZE)
    private val target = ByteArray(Protocol.HEAP_SIZE)
    private var virgin = true   // fresh heap: device contents unknown
    var packetIndex = startIndex and 0x3FF
        private set

    fun setBytes(offset: Int, data: ByteArray) {
        System.arraycopy(data, 0, target, offset, data.size)
    }

    fun seedIndex(i: Int) { packetIndex = i and 0x3FF }

    /** Adopt an in-progress session: device already has the program and
     *  some frame; do NOT do the virgin full-heap write (rewriting the
     *  program area wipes frame data — firmware law). */
    fun adoptState() { virgin = false }

    fun markUnknownFrameArea(from: Int) {
        // force full rewrite of frame area on next drain (mood-switch sync)
        for (i in from until Protocol.HEAP_SIZE)
            deviceState[i] = (target[i].toInt().inv() and 0xFF).toByte()
    }

    /** All packets needed to bring the device to `target`. */
    fun drain(): List<ByteArray> {
        if (virgin) {
            // Python remote_heap maps UNKNOWN bytes to ~target, forcing a
            // full-heap write (zeros arrive run-length-compressed)
            for (i in deviceState.indices)
                deviceState[i] = (target[i].toInt().inv() and 0xFF).toByte()
            virgin = false
        }
        val out = mutableListOf<ByteArray>()
        while (true) {
            val regions = HeapDiff.computeDiff(deviceState, target)
            if (regions.isEmpty()) break
            val builder = PacketBuilder(Protocol.MAX_PACKET_BYTES)
            builder.sysexHeader(deviceIndex)
            builder.beginDataChanges(packetIndex)
            val enc = DataChangeEncoder(builder.writer)
            val resultState = deviceState.copyOf()
            val complete = HeapDiff.encodeLimited(
                enc, builder.writer, regions, target, resultState)
            if (resultState.contentEquals(deviceState)) break
            enc.end(complete)
            out.add(builder.build())
            System.arraycopy(resultState, 0, deviceState, 0, resultState.size)
            packetIndex = (packetIndex + 1) and 0x3FF
        }
        return out
    }
}
