/*
 * Poképad — HERO ART: hand-authored 15x15 pixel art for iconic species, so each
 * one is instantly recognizable (Pikachu ≠ Raichu at a glance) instead of a
 * generic type-colored archetype. Renderer uses this when present and falls back
 * to the procedural archetype otherwise. All ORIGINAL art (the covenant).
 *
 * Each entry: a palette (char → 0xRRGGBB) + 15 rows of 15 chars. '.' = empty.
 * Common chars: K=near-black detail, W=white, E=eye. Outline is added by the
 * renderer, so author the FILL only.
 */
object HeroArt {
    private val COMMON = mapOf('.' to 0, 'K' to 0x0A0A0F, 'W' to 0xF4F4F4, 'E' to 0x141014)

    private class Hero(val pal: Map<Char, Int>, val rows: List<String>)

    private fun render(h: Hero): IntArray {
        val out = IntArray(225)
        for (y in 0 until 15) {
            val row = h.rows.getOrElse(y) { "" }
            for (x in 0 until 15) {
                val c = row.getOrElse(x) { '.' }
                out[y * 15 + x] = h.pal[c] ?: COMMON[c] ?: 0
            }
        }
        return out
    }

    /** 15x15 front pixels, or null if not hand-authored. */
    fun px(species: String): IntArray? = ART[species]?.let { render(it) }
    /** 15x15 back pixels (first-person player side / face-off), or null. */
    fun pxBack(species: String): IntArray? = BACK[species]?.let { render(it) }

    fun has(species: String) = ART.containsKey(species)
    fun hasBack(species: String) = BACK.containsKey(species)

    private fun hero(pal: Map<Char, Int>, vararg rows: String) = Hero(pal, rows.toList())

    private val ART: Map<String, Hero> = mapOf(
        // ── PIKACHU ── yellow, long black-tipped ears, red cheeks, bolt tail
        "pikachu" to hero(
            mapOf('Y' to 0xF6D02E, 'y' to 0xD9AE1E, 'r' to 0xE24B3A, 'b' to 0xC79A3A, 'B' to 0x8A6A22),
            "..K.......K....",
            "..KY.....YK....",
            "..KY.....YK....",
            "..YYY...YYY....",
            ".YYYYYYYYYYY...",
            ".YYYYYYYYYYY...",
            ".YWEYYYYYEWY.B.",
            ".YYYYYYYYYYYbB.",
            ".rYYKYYYKYYrbB.",
            "..YYYYYYYYYbb..",
            "..YYYYYYYYYb...",
            "..YYYYYYYYY....",
            "..YY.YYY.YY....",
            "..K...Y...K....",
            "..............."),

        // ── CHARMANDER ── orange, cream belly, flame on tail tip
        "charmander" to hero(
            mapOf('O' to 0xF08838, 'o' to 0xD06A24, 'c' to 0xF4D8A8, 'F' to 0xF5C842, 'f' to 0xF08020, 'g' to 0xE04010),
            ".....OOO.......",
            "....OOOOOO.....",
            "...OOOOOOOO...g",
            "...OEOOOEOO..fF",
            "...OOOOOOOO..Ff",
            "....OOOOO...ffO",
            "...OOOOOOO..OO.",
            "..OOcccccOO....",
            "..OcccccccO....",
            "..OcccccccO....",
            "..OOcccccOO....",
            "...OOcccOO.....",
            "...oO...Oo.....",
            "...o.....o.....",
            "..............."),

        // ── SQUIRTLE ── blue head/limbs, brown shell, cream plastron
        "squirtle" to hero(
            mapOf('B' to 0x5AA0E6, 'b' to 0x3A78C0, 'S' to 0xC08840, 's' to 0x9A6A2E, 'c' to 0xF0E0B0),
            "....BBBBB......",
            "...BBBBBBB.....",
            "..BBEBBBEBB....",
            "..BBBBBBBBB....",
            "..bBBBBBBBb....",
            "...BBBBBBB.....",
            "..SSSSSSSSS....",
            ".SScccccccSS...",
            ".ScscscscscS...",
            ".ScccccccccS...",
            ".SScscscscSS...",
            "..SSSSSSSSS....",
            "..bB.....Bb....",
            "..b.......b....",
            "..............."),

        // ── BULBASAUR ── teal body, dark spots, green bulb on back
        "bulbasaur" to hero(
            mapOf('T' to 0x6FC8B0, 't' to 0x4C9C86, 'G' to 0x4CA83C, 'g' to 0x357A28, 's' to 0x2A5A48),
            "....gGGGg......",
            "...GGGGGGG.....",
            "..GgGGGGGgG....",
            "..TTTTTTTTT....",
            ".TTEsTTTsETT...",
            ".TTTTTTTTTTT...",
            ".sTTTTTTTTTs...",
            ".TTsTTTTTsTT...",
            "..TTTTTTTTT....",
            "..sTTTTTTTs....",
            "..TTsTTTsTT....",
            "..TT.....TT....",
            ".tT.......Tt...",
            ".t.........t...",
            "..............."),

        // ── GENGAR ── purple round body, big toothy grin, back spikes
        "gengar" to hero(
            mapOf('P' to 0x7A5AB0, 'p' to 0x5A3E86, 'W' to 0xF4F4F4, 'r' to 0xC03050),
            "..p.p.p.p.p....",
            "..PPPPPPPPP....",
            ".PPPPPPPPPPP...",
            ".PPEWPPPWEPP...",
            ".PPWKPPPKWPP...",
            ".PPPPPPPPPPP...",
            ".PWWWWWWWWWP...",
            ".PWKWKWKWKWP...",
            ".PPWWWWWWWPP...",
            "..PPPPPPPPP....",
            ".pPPPPPPPPp....",
            ".pPP.....PPp...",
            "..p.......p....",
            "..pp.....pp....",
            "..............."),

        // ── SNORLAX ── big blue-grey body, cream belly, sleepy face
        "snorlax" to hero(
            mapOf('B' to 0x5A6E7A, 'b' to 0x3E4E58, 'c' to 0xE8D8B0, 'C' to 0xD0BE94),
            "....BBBBBBB....",
            "..BBBBBBBBBBB..",
            ".BBBBBBBBBBBBB.",
            ".BBKBBBBBKBBBB.",
            ".BBBBBBBBBBBBB.",
            "BBBcccccccccBB.",
            "BbcccccccccccbB",
            "BcccccccccccccB",
            "BcccccccccccccB",
            "BbcccccccccccbB",
            ".BBcccccccccBB.",
            ".BBCCCCCCCCCBB.",
            "..BB.......BB..",
            "..bb.......bb..",
            "..............."),

        // ── JIGGLYPUFF ── pink balloon, big eyes, tuft of hair
        "jigglypuff" to hero(
            mapOf('P' to 0xF0B8C8, 'p' to 0xD892A8, 'B' to 0x40C0E0, 'W' to 0xF8F4F6),
            ".....ppp.......",
            "....pPPPp......",
            "...PPPPPPP.....",
            "..PPPPPPPPP....",
            ".PPPPPPPPPPP...",
            ".PPBWPPPBWPP...",   // big blue eyes with white glint
            ".PPWBPPPWBPP...",
            ".PPPPPKPPPPP...",
            ".PPPPPPPPPPP...",
            ".pPPPPPPPPPp...",
            "..PPPPPPPPP....",
            "...PPPPPPP.....",
            "....p...p......",
            "...............",
            "..............."),

        // ── MAGIKARP ── red fish, big lips, yellow whiskers, tail fin
        "magikarp" to hero(
            mapOf('R' to 0xE8503A, 'r' to 0xC03A28, 'Y' to 0xF5C842, 'W' to 0xF4F4F4, 't' to 0xF0E0A0),
            "...............",
            "...RRRRR....t..",
            "..RRRRRRR..tt..",
            ".RRRRRRRRRtttR.",
            "RRWERRRRRRRttRR",
            "RRWERRRRRRRttR.",
            "YRRRRRRRRRtttR.",
            "Y.RRRRRRR..tt..",
            "Y..RRRRR....t..",
            "...rrrrr.......",
            "...............",
            "...............",
            "...............",
            "...............",
            "..............."),

        // ── CHARIZARD ── orange dragon, teal wings, flame tail, cream belly
        "charizard" to hero(
            mapOf('O' to 0xF08838, 'o' to 0xD06A24, 'c' to 0xF4D8A8, 'w' to 0x3E7C74, 'W' to 0x5AA096,
                'F' to 0xF5C842, 'f' to 0xF08020, 'H' to 0xEFE0C0),
            "......OHO......",
            ".....OOOOO.....",
            ".....OEOEO.....",
            "wW...OOOOO...Ww",
            "wWW.OOcccOO.WWw",
            "wWWWOcccccOWWWw",
            ".wWWOcccccOWWw.",
            "...OOcccccOO..f",
            "...OcccccccOffF",
            "...OcccccccO.Ff",
            "...OOcccccOO.f.",
            "....OO.O.OO....",
            "....o.....o....",
            "...............",
            "..............."),

        // ── BLASTOISE ── blue turtle, brown shell, twin water cannons
        "blastoise" to hero(
            mapOf('B' to 0x5AA0E6, 'b' to 0x3A78C0, 'S' to 0xB07838, 's' to 0x8A5E28, 'C' to 0x9AA6B0, 'c' to 0x70808C),
            "....BBBBB......",
            "...BBEBBEBB....",
            "...BBBBBBBB....",
            ".Cc.BBBBB.cC...",
            ".CcSSSSSSScC...",
            ".ccSssssssScc..",
            "..SsSsSsSsSS...",
            "..SSsSsSsSsS...",
            "..SsSsSsSsSS...",
            "..SSssssssSS...",
            "..bSSSSSSSSb...",
            "..bB.....Bb....",
            "..b.......b....",
            "...............",
            "..............."),

        // ── VENUSAUR ── teal body, huge flower + leaves on its back
        "venusaur" to hero(
            mapOf('T' to 0x6F9CC0, 't' to 0x4C7C9E, 'R' to 0xE86A9A, 'r' to 0xC04878, 'y' to 0xF5D24A,
                'G' to 0x4CA83C, 'g' to 0x357A28, 's' to 0x2A4A5E),
            "..gG.gGg.Gg....",
            "...RRRRRRR.....",
            "..RRRyyyRRR....",
            "..RRyyyyyRR....",
            "...RRRyyRR.....",
            ".TTTTTTTTTTT...",
            "TTEsTTTTTsETT..",
            "TTTTTTTTTTTTT..",
            "sTTTTTTTTTTTs..",
            "TTsTTTTTTsTTT..",
            ".TTTTTTTTTTT...",
            ".TT.TT.TT.TT...",
            "tT.t.....t.Tt..",
            "...............",
            "..............."),

        // ── MEWTWO ── tall grey-purple psychic, tube neck, long tail
        "mewtwo" to hero(
            mapOf('P' to 0xC8C0D8, 'p' to 0x9A90B4, 'v' to 0x8A5AB0, 'E' to 0x6A50A0, 'W' to 0xF4F4F4),
            "....PPPP.......",
            "...PPPPPP......",
            "...PPvvPP......",
            "...PEWPEW......",
            "....PPPP.......",
            "...ppPPpp......",
            "..PP.PP.PP.....",
            ".PP..PP..PP.vv.",
            ".P...PP...P.v..",
            ".....PP....vv..",
            "....PPPP..vv...",
            "...PP..PP.v....",
            "..PPp..pPP.....",
            "..pp....pp.....",
            "..............."),

        // ── EEVEE ── brown fox, big ears, cream ruff, bushy tail
        "eevee" to hero(
            mapOf('B' to 0xB0824A, 'b' to 0x8A6030, 'c' to 0xF0DCA8, 'C' to 0xD8BE84, 'K' to 0x0A0A0F),
            "..b.......b....",
            ".bBb.....bBb...",
            ".BBBb...bBBB...",
            ".BBBBBBBBBBB...",
            ".BBEBBBBBEBB...",
            ".BBBBBKBBBBB...",
            ".cccccccccccc..",
            "..CcccccccC....",
            "c.BBcccccBB....",
            "ccBBBBBBBBB....",
            "ccc.BBBBB.b....",
            "..BB.B.B.BB....",
            "...............",
            "...............",
            "..............."),

        // ── GYARADOS ── blue sea-serpent, yellow crest + whiskers, fierce
        "gyarados" to hero(
            mapOf('B' to 0x4C82C8, 'b' to 0x2E5896, 'Y' to 0xF5C842, 'W' to 0xF4F4F4, 'K' to 0x0A0A0F),
            "..Y.Y...Y.Y....",
            ".YbBBBBBBBbY...",
            ".BBWEBBBWEBB...",
            ".BBBBBBBBBBB...",
            "Y.BBBKKKBBB.Y..",
            "YY.BBBBBBB.YY..",
            "...BBBBBBB.....",
            "....BBBBB......",
            "...bBBBBBb.....",
            "..BBBBBBBBB....",
            "..BBb...bBB....",
            "..b.......b....",
            "...............",
            "...............",
            "..............."),

        // ── MEOWTH ── tan cat, gold charm, whiskers, coiled tail
        "meowth" to hero(
            mapOf('T' to 0xE8D8A8, 't' to 0xC0A870, 'G' to 0xF5C842, 'g' to 0xC89A28, 'W' to 0xF4F4F4, 'K' to 0x0A0A0F),
            "..t.t...t.t....",
            ".tTt.....tTt...",
            ".TTTgGgTTT.....",
            ".TTTGGGTTT.....",
            ".TTTTTTTTTT....",
            "WTETTTTTETW....",
            ".WTTTKTTTW.....",
            ".TTTtttTTT.....",
            "..TTTTTTTT.....",
            "..TTTTTTTTt....",
            "..TTTTTTt.tt...",
            "..tT.TT.Tt.t...",
            "...............",
            "...............",
            "..............."),

        // ── PSYDUCK ── yellow duck, blank stare, hands on head, bill
        "psyduck" to hero(
            mapOf('Y' to 0xF6D84A, 'y' to 0xD8B828, 'o' to 0xE89A38, 'W' to 0xF8F4F0, 'K' to 0x1A1A1E),
            "...K.K.K.......",
            "..YYYYYYY......",
            ".YYYYYYYYY.....",
            ".YWKYYYWKY.....",
            ".YYYYYYYYY.....",
            "..ooooooo......",
            ".YyYYYYYyY.....",
            "y.YYYYYYY.y....",
            "y.YYYYYYY.y....",
            "..YYYYYYY......",
            "..YYYYYYY......",
            "..YY...YY......",
            "..oo...oo......",
            "...............",
            "..............."),

        // ── SALAMENCE ── blue dragon, big red wings, four legs (NICK's ace)
        "salamence" to hero(
            mapOf('B' to 0x3E76C8, 'b' to 0x28527E, 'R' to 0xD84038, 'r' to 0xA82A28),
            "......BBB......",
            ".....BBEBB.....",
            ".....BBBBB.....",
            "R....BBBBB....R",
            "RRR.BBBBBBB.RRR",
            "rRRRBBBBBBBRRRr",
            ".rR.BBBBBBB.Rr.",
            "...BBBBBBBBB...",
            "..BBBBBBBBBBB..",
            "..BBBBBBBBBBB..",
            "..BBBBBBBBBBB..",
            "..BB.BB.BB.BB..",
            "..b..b...b..b..",
            "...............",
            "..............."),

        // ── MAGCARGO ── molten snail, rocky grey shell, glowing lava body
        "magcargo" to hero(
            mapOf('O' to 0xF06A2A, 'o' to 0xC84818, 'S' to 0x8A8078, 's' to 0x5E564E, 'F' to 0xF5C842),
            "...............",
            "....SSSSS......",
            "...SsSsSsS.....",
            "..SSsSsSsSS....",
            "..SsSsSsSsS....",
            ".OOSsSsSsSOO...",
            ".OOOOOOOOOOO...",
            "OOFOOOOOOOFO...",
            "OOOOOOOOOOOO...",
            "OOEOOOOOOEOO...",
            ".OOOOOOOOOO....",
            ".ooooooooo.....",
            "...............",
            "...............",
            "..............."),

        // ── SMEARGLE ── painter dog, green beret, paint-tipped tail
        "smeargle" to hero(
            mapOf('W' to 0xE8DCC0, 'w' to 0xC0B090, 'G' to 0x4CA83C, 'g' to 0x357A28, 'R' to 0xD84860, 'K' to 0x1A1A1E),
            "....GGGGG......",
            "...GgGGGgG.....",
            "..w.WWWWW.w....",
            ".ww.WWWWW.ww...",
            ".w.WWEWEWW.w...",
            "...WWWKWWW.....",
            "...WWWWWWW...R.",
            "..WWWWWWWWWRRR.",
            "..WWWWWWWWW.R..",
            "..WWWWWWWWW....",
            "..WWWWWWWWW....",
            "..WW.WW.WW.....",
            "..w...w..w.....",
            "...............",
            "..............."),

        // ── SCEPTILE ── forest gecko, backswept crest, red belly, fir tail
        "sceptile" to hero(
            mapOf('G' to 0x58B848, 'g' to 0x3A8A30, 'd' to 0x246018, 'Y' to 0xE0D048, 'R' to 0xC84040),
            "....ggg........",
            "...gGGGgg......",
            "...GEGGGgg.....",
            "...GGGGGg......",
            "....GGGG.......",
            "..G.gGGg..d....",
            ".GGgGGGGg.dd...",
            "..GgGRRGg.ddd..",
            "...gGRRGgddY...",
            "...gGGGGgdY....",
            "...gGGGGgdd....",
            "..gGg..gGgd....",
            "..gg....gg.....",
            "..g......g.....",
            "..............."),

        // ── BLAZIKEN ── fire fighter, cream head plumes, flame wrists
        "blaziken" to hero(
            mapOf('R' to 0xD03828, 'r' to 0x9E2418, 'c' to 0xF0E0B8, 'Y' to 0xF5C842,
                  'O' to 0xF08020, 's' to 0x8A8480),
            "..c.......c....",
            "..cc.....cc....",
            "...ccccccc.....",
            "...cRRRRRc.....",
            "...RERRRER.....",
            "...RRRRRRR.....",
            "..ccRRRRRcc....",
            ".YY.RRRRR.YY...",
            ".YO.RRRRR.OY...",
            "....RRRRR......",
            "....rRRRr......",
            "....sR.Rs......",
            "....s...s......",
            "...ss...ss.....",
            "..............."),

        // ── SWAMPERT ── mud fish, head fin, orange gills, cream belly
        "swampert" to hero(
            mapOf('B' to 0x4888C8, 'b' to 0x2E608E, 'O' to 0xE87838, 'c' to 0xD8E4EC, 'F' to 0x365070),
            ".....FFF.......",
            "....FFFFF......",
            "..BBBBBBBBB....",
            ".BBBBBBBBBBB...",
            ".BBEBBBBBEBB...",
            ".OOBBBBBBBOO...",
            ".OOBBbbbBBOO...",
            "..BBBBBBBBB....",
            "..BBcccccBB....",
            ".BBBcccccBBB...",
            ".BBBcccccBBB...",
            "..BBBcccBBB....",
            "..bB..FF.Bb....",
            "..b...FF..b....",
            "..............."),

        // ── RAYQUAZA ── sky serpent coiled, yellow rings, horned head
        "rayquaza" to hero(
            mapOf('G' to 0x2E9A48, 'g' to 0x1E6A30, 'Y' to 0xE8D040, 'R' to 0xC03040),
            "..gg.....gg....",
            "..GGGGGGGGG....",
            "..GGEGGGEGG....",
            "...GGRRRGG.....",
            "....GGGGG......",
            ".....gGGGg.....",
            "......gGGGg....",
            "....Y.gGGGGY...",
            "...gGGGGgY.....",
            "..gGGGGg.......",
            "..GGGYg........",
            "..gGGGGGgg.....",
            "...ggGGGGGgg...",
            ".....Y..ggGY...",
            "..............."),

        // ── METAGROSS ── steel spider-tank, silver X face, red eyes
        "metagross" to hero(
            mapOf('B' to 0x4A6AB8, 'b' to 0x32498A, 'S' to 0xC0C8D0, 's' to 0x808A9A, 'R' to 0xD84038),
            "...............",
            ".S...........S.",
            ".SsBBBBBBBBBsS.",
            ".SBBSBBBBSBBS..",
            "..BBSSBBSSBB...",
            "..BRBSSSSBRB...",
            "..BRBSSSSBRB...",
            "..BBSSBBSSBB...",
            "..BBSBBBBSBB...",
            "..BbBBBBBBbB...",
            "..bBBBBBBBBb...",
            ".Ss.b....b.sS..",
            ".S..b....b..S..",
            ".ss..........s.",
            "..............."),

        // ── GARDEVOIR ── green bob, white gown, red chest fin
        "gardevoir" to hero(
            mapOf('W' to 0xF4F2EE, 'w' to 0xC4C4CE, 'G' to 0x48A878, 'g' to 0x2F7A56, 'R' to 0xE04858),
            "....GGGGG......",
            "...GGGGGGG.....",
            "...GGWWWGG.....",
            "...GWEWEWG.....",
            "...GGWWWGG.....",
            "..G..WWW..G....",
            ".....WRW.......",
            "..W..WRW..W....",
            "...W.WWW.W.....",
            "....WWWWW......",
            "...WWWWWWW.....",
            "..WWWwWwWWW....",
            ".WWWwWWWwWWW...",
            ".WwWWWWWWWwW...",
            "..............."),

        // ── FLYGON ── desert dragonfly, goggle eyes, red-rimmed wings
        "flygon" to hero(
            mapOf('G' to 0x88C858, 'g' to 0x5A9A38, 'R' to 0xD84038, 'd' to 0x3E7028),
            "..g.......g....",
            "...GGGGGGG.....",
            "..GEEGGGEEG....",
            "..GEEGGGEEG....",
            "...GGGGGGG.....",
            "R..gGGGGGg..R..",
            "RR.GGGGGGG.RR..",
            ".RGgGGGGGgGR...",
            ".RGGgGGGgGGR...",
            "..RG.GGG.GR....",
            "....GGGGG......",
            "....gG.Gg......",
            "....g...g.RR...",
            "..........gRR..",
            "..............."),

        // ── MILOTIC ── elegant serpent, red brow fins, blue tail fan
        "milotic" to hero(
            mapOf('C' to 0xEADCC4, 'c' to 0xC4AE8E, 'R' to 0xC84858, 'r' to 0x8E3040,
                  'B' to 0x5878C8, 'b' to 0x3A5490),
            "....CCC........",
            ".R.CCCCC.R.....",
            ".RRCCECCRR.....",
            "..RCCCCCR......",
            "....CCC........",
            "....cCC........",
            ".....CCc.......",
            ".....cCC.......",
            "....CCc..br....",
            "...CCC...Bb....",
            "..cCC...BBb....",
            "..CCC..bBBB....",
            "...cCCCBbBb....",
            ".....BB.bB.....",
            "..............."))

    // ── BACK VIEWS (no face; distinctive back features) ──────────────────
    private val BACK: Map<String, Hero> = mapOf(
        "pikachu" to hero(
            mapOf('Y' to 0xF6D02E, 'y' to 0xB98A22, 'b' to 0xC79A3A, 'B' to 0x8A6A22),
            "..K.......K....",
            "..KY.....YK....",
            "..KY.....YK....",
            "..YYY...YYY....",
            ".YYYYYYYYYYY...",
            ".YYYYYYYYYYY...",
            ".YYYYYYYYYYY.B.",
            ".YyyYYYyyYYYbB.",
            ".YyyYYYyyYYYbB.",
            "..YYYYYYYYYbb..",
            "..YYYYYYYYYb...",
            "..YYYYYYYYY....",
            "..YY.YYY.YY....",
            "..K...Y...K....",
            "..............."),
        "charmander" to hero(
            mapOf('O' to 0xF08838, 'o' to 0xD06A24, 'F' to 0xF5C842, 'f' to 0xF08020, 'g' to 0xE04010),
            ".....OOO.......",
            "....OOOOOO.....",
            "...OOOOOOOO...g",
            "...OOOOOOOO..fF",
            "...OOOOOOOO..Ff",
            "....OOOOO...ffO",
            "...OOOOOOO..OO.",
            "..OOOOOOOOO....",
            "..OOOOOOOOO....",
            "..OOOOOOOOO....",
            "..OOOOOOOOO....",
            "...OOOOOOO.....",
            "...oO...Oo.....",
            "...o.....o.....",
            "..............."),
        "squirtle" to hero(
            mapOf('B' to 0x5AA0E6, 'b' to 0x3A78C0, 'S' to 0xC08840, 's' to 0x9A6A2E),
            "....BBBBB......",
            "...BBBBBBB.....",
            "...BBBBBBB.....",
            "..SSSSSSSSS....",
            ".SSsSsSsSsSS...",
            ".SsSsSsSsSsS...",
            ".SSsSsSsSsSS...",
            ".SsSsSsSsSsS...",
            ".SSsSsSsSsSS...",
            ".SsSsSsSsSsS...",
            "..SSSSSSSSS....",
            "..bB.....Bb....",
            "..b.......b....",
            "...............",
            "..............."),
        "bulbasaur" to hero(
            mapOf('T' to 0x6FC8B0, 't' to 0x4C9C86, 'G' to 0x4CA83C, 'g' to 0x357A28, 's' to 0x2A5A48),
            "..gG.gGg.Gg....",
            "..GGGGGGGGG....",
            ".GGGGGGGGGGG...",
            ".GgGGGGGGGgG...",
            ".GGGGGGGGGGG...",
            "..GGGGGGGGG....",
            ".TTTTTTTTTTT...",
            ".TTTTTTTTTTT...",
            ".sTTTTTTTTTs...",
            ".TTsTTTTTsTT...",
            "..TTTTTTTTT....",
            "..TT.TT.TT.T...",
            ".tT.......Tt...",
            "...............",
            "..............."),
        "gengar" to hero(
            mapOf('P' to 0x7A5AB0, 'p' to 0x5A3E86),
            "..p.p.p.p.p....",
            "..PPPPPPPPP....",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            "..PPPPPPPPP....",
            ".pPPPPPPPPp....",
            ".pPP.....PPp...",
            "..p.......p....",
            "..pp.....pp....",
            "..............."),
        "snorlax" to hero(
            mapOf('B' to 0x5A6E7A, 'b' to 0x3E4E58),
            "....BBBBBBB....",
            "..BBBBBBBBBBB..",
            ".BBBBBBBBBBBBB.",
            ".BBBBBBBBBBBBB.",
            ".BBBBBBBBBBBBB.",
            "BBBBBBBBBBBBBBB",
            "BbBBBBBBBBBBBbB",
            "BBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBB",
            "BbBBBBBBBBBBBbB",
            ".BBBBBBBBBBBBB.",
            ".BBBBBBBBBBBBB.",
            "..BB.......BB..",
            "..bb.......bb..",
            "..............."),
        "jigglypuff" to hero(
            mapOf('P' to 0xF0B8C8, 'p' to 0xD892A8),
            "....ppP........",
            "...pPPPp.......",
            "...PPPPPPP.....",
            "..PPPPPPPPP....",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".PPPPPPPPPPP...",
            ".pPPPPPPPPPp...",
            "..PPPPPPPPP....",
            "...PPPPPPP.....",
            "....p...p......",
            "...............",
            "..............."),
        "magikarp" to hero(
            mapOf('R' to 0xE8503A, 'r' to 0xC03A28, 't' to 0xF0E0A0),
            "...............",
            "......RRRRR.t..",
            ".....RRRRRRtt..",
            "....RRRRRRttttR",
            "...RRRRRRRRttRR",
            "...RRRRRRRRttR.",
            "...RRRRRRRttttR",
            "....RRRRRR.tt..",
            ".....RRRRR..t..",
            "......rrr......",
            "...............",
            "...............",
            "...............",
            "...............",
            "..............."),
        "charizard" to hero(
            mapOf('O' to 0xF08838, 'o' to 0xD06A24, 'w' to 0x3E7C74, 'W' to 0x5AA096, 'F' to 0xF5C842, 'f' to 0xF08020),
            "......OOO......",
            ".....OOOOO.....",
            "wW...OOOOO...Ww",
            "wWW.OOOOOOO.WWw",
            "wWWWOOOOOOOWWWw",
            ".wWWOOOOOOOWWw.",
            "..wWOOOOOOOWw..",
            "...OOOOOOOOO..f",
            "...OOOOOOOOOffF",
            "...OOOOOOOOO.Ff",
            "...OOOOOOOOO.f.",
            "....OO.O.OO....",
            "....o.....o....",
            "...............",
            "..............."),
        "blastoise" to hero(
            mapOf('B' to 0x5AA0E6, 'b' to 0x3A78C0, 'S' to 0xB07838, 's' to 0x8A5E28, 'C' to 0x9AA6B0, 'c' to 0x70808C),
            "...C.....C.....",
            "...C.....C.....",
            "..CcBBBBBcC....",
            "..cSSSSSSSc....",
            ".SSsSsSsSsSS...",
            ".SsSsSsSsSsS...",
            ".SSsSsSsSsSS...",
            ".SsSsSsSsSsS...",
            ".SSsSsSsSsSS...",
            ".SsSsSsSsSsS...",
            "..SSSSSSSSS....",
            "..bB.....Bb....",
            "..b.......b....",
            "...............",
            "..............."),
        "venusaur" to hero(
            mapOf('T' to 0x6F9CC0, 't' to 0x4C7C9E, 'R' to 0xE86A9A, 'y' to 0xF5D24A, 'G' to 0x4CA83C, 'g' to 0x357A28, 's' to 0x2A4A5E),
            "..gG.gGg.Gg....",
            "...RRRRRRR.....",
            "..RRRyyyRRR....",
            "..RRyyyyyRR....",
            "...RRRyyRR.....",
            ".GgGGGGGGGgG...",
            ".TTTTTTTTTTT...",
            ".TTTTTTTTTTT...",
            ".sTTTTTTTTTs...",
            ".TTsTTTTTsTT...",
            ".TT.TT.TT.TT...",
            "tT.t.....t.Tt..",
            "...............",
            "...............",
            "..............."),
        "mewtwo" to hero(
            mapOf('P' to 0xC8C0D8, 'p' to 0x9A90B4, 'v' to 0x8A5AB0),
            "....PPPP.......",
            "...PPPPPP......",
            "...PPPPPP......",
            "...PPPPPP......",
            "....PPPP.......",
            "...ppPPpp......",
            "..PP.PP.PP.....",
            ".PP..PP..PP.vv.",
            ".P...PP...P.v..",
            ".....PP....vv..",
            "....PPPP..vv...",
            "...PP..PP.v....",
            "..PPp..pPP.....",
            "..pp....pp.....",
            "..............."),
        "eevee" to hero(
            mapOf('B' to 0xB0824A, 'b' to 0x8A6030, 'c' to 0xF0DCA8, 'C' to 0xD8BE84),
            "..b.......b....",
            ".bBb.....bBb...",
            ".BBBb...bBBB...",
            ".BBBBBBBBBBB...",
            ".BBBBBBBBBBB...",
            ".BBBBBBBBBBB...",
            "..BBBBBBBBB....",
            "c.BBBBBBBBB....",
            "cc.BBBBBBB.....",
            "ccc.BBBBB......",
            "cc..BBBBB......",
            "..BB.B.B.BB....",
            "...............",
            "...............",
            "..............."),
        "gyarados" to hero(
            mapOf('B' to 0x4C82C8, 'b' to 0x2E5896, 'Y' to 0xF5C842),
            "..Y.Y...Y.Y....",
            ".YbBBBBBBBbY...",
            ".BBBBBBBBBBB...",
            ".BBBBBBBBBBB...",
            "Y.BBBBBBBBB.Y..",
            "YY.BBBBBBB.YY..",
            "...BBBBBBB.....",
            "....BBBBB......",
            "...bBBBBBb.....",
            "..BBBBBBBBB....",
            "..BBb...bBB....",
            "..b.......b....",
            "...............",
            "...............",
            "..............."),
        "meowth" to hero(
            mapOf('T' to 0xE8D8A8, 't' to 0xC0A870),
            "..t.t...t.t....",
            ".tTt.....tTt...",
            ".TTTTTTTTTT....",
            ".TTTTTTTTTT....",
            ".TTTTTTTTTT....",
            ".TTTTTTTTTT....",
            ".TTTTTTTTTT....",
            ".TTTtttTTT.....",
            "..TTTTTTTT.....",
            "..TTTTTTTTt....",
            "..TTTTTTt.tt...",
            "..tT.TT.Tt.t...",
            "...............",
            "...............",
            "..............."),
        "psyduck" to hero(
            mapOf('Y' to 0xF6D84A, 'y' to 0xD8B828, 'o' to 0xE89A38, 'K' to 0x1A1A1E),
            "...K.K.K.......",
            "..YYYYYYY......",
            ".YYYYYYYYY.....",
            ".YYYYYYYYY.....",
            ".YYYYYYYYY.....",
            ".YYYYYYYYY.....",
            ".YyYYYYYyY.....",
            "y.YYYYYYY.y....",
            "y.YYYYYYY.y....",
            "..YYYYYYY......",
            "..YYYYYYY......",
            "..YY...YY......",
            "..oo...oo......",
            "...............",
            "..............."),
        "salamence" to hero(
            mapOf('B' to 0x3E76C8, 'b' to 0x28527E, 'R' to 0xD84038, 'r' to 0xA82A28),
            "......BBB......",
            ".....BBBBB.....",
            ".....BBBBB.....",
            "R....BBBBB....R",
            "RRR.BBBBBBB.RRR",
            "rRRRBBBBBBBRRRr",
            ".rR.BBBBBBB.Rr.",
            "...BBBBBBBBB...",
            "..BBBBBBBBBBB..",
            "..BBBBBBBBBBB..",
            "..BBBBBBBBBBB..",
            "..BB.BB.BB.BB..",
            "..b..b...b..b..",
            "...............",
            "..............."),
        "magcargo" to hero(
            mapOf('O' to 0xF06A2A, 'o' to 0xC84818, 'S' to 0x8A8078, 's' to 0x5E564E),
            "...............",
            "....SSSSS......",
            "...SsSsSsS.....",
            "..SSsSsSsSS....",
            "..SsSsSsSsS....",
            ".OOSsSsSsSOO...",
            ".OOOOOOOOOOO...",
            "OOOOOOOOOOOO...",
            "OOOOOOOOOOOO...",
            "OOOOOOOOOOOO...",
            ".OOOOOOOOOO....",
            ".ooooooooo.....",
            "...............",
            "...............",
            "..............."),
        "smeargle" to hero(
            mapOf('W' to 0xE8DCC0, 'w' to 0xC0B090, 'G' to 0x4CA83C, 'g' to 0x357A28, 'R' to 0xD84860),
            "....GGGGG......",
            "...GgGGGgG.....",
            "..w.WWWWW.w....",
            ".ww.WWWWW.ww...",
            ".w.WWWWWWW.w...",
            "...WWWWWWW.....",
            "...WWWWWWW...R.",
            "..WWWWWWWWWRRR.",
            "..WWWWWWWWW.R..",
            "..WWWWWWWWW....",
            "..WWWWWWWWW....",
            "..WW.WW.WW.....",
            "..w...w..w.....",
            "...............",
            "..............."),

        "sceptile" to hero(
            mapOf('G' to 0x58B848, 'g' to 0x3A8A30, 'd' to 0x246018, 'Y' to 0xE0D048),
            "....ggg........",
            "...ggGGg.......",
            "...gGGGG.......",
            "...GGGGG.......",
            "....GGGG.......",
            "..G.gYGg..d....",
            ".GGgGGYGg.dd...",
            "..GgGGYGg.ddd..",
            "...gGGYGgddY...",
            "...gGGGGgdY....",
            "...gGGGGgdd....",
            "..gGg..gGgd....",
            "..gg....gg.....",
            "..g......g.....",
            "..............."),

        "blaziken" to hero(
            mapOf('R' to 0xD03828, 'r' to 0x9E2418, 'c' to 0xF0E0B8, 'Y' to 0xF5C842,
                  'O' to 0xF08020, 's' to 0x8A8480),
            "..c.......c....",
            "..cc.....cc....",
            "...ccccccc.....",
            "...ccccccc.....",
            "...RRRRRRR.....",
            "...RRRRRRR.....",
            "..cRRrRrRRc....",
            ".YY.RrRrR.YY...",
            ".YO.RRRRR.OY...",
            "....RRRRR......",
            "....rRRRr......",
            "....sR.Rs......",
            "....s...s......",
            "...ss...ss.....",
            "..............."),

        "swampert" to hero(
            mapOf('B' to 0x4888C8, 'b' to 0x2E608E, 'O' to 0xE87838, 'F' to 0x365070),
            ".....FFF.......",
            "....FFFFF......",
            "..BBBBBBBBB....",
            ".BBBBBBBBBBB...",
            ".BBBBBBBBBBB...",
            ".OOBBBBBBBOO...",
            ".OOBBBBBBBOO...",
            "..BBBBBBBBB....",
            "..BBBbBbBBB....",
            ".BBBBbBbBBBB...",
            ".BBBBBBBBBBB...",
            "..BBBBBBBBB....",
            "..bB..FF.Bb....",
            "..b...FF..b....",
            "..............."),

        "rayquaza" to hero(
            mapOf('G' to 0x2E9A48, 'g' to 0x1E6A30, 'Y' to 0xE8D040, 'R' to 0xC03040),
            "..gg.....gg....",
            "..GGGGGGGGG....",
            "..GGGGGGGGG....",
            "...GGGGGGG.....",
            "....GGGGG......",
            ".....gGGGg.....",
            "......gGGGg....",
            "....Y.gGGGGY...",
            "...gGGGGgY.....",
            "..gGGGGg.......",
            "..GGGYg........",
            "..gGGGGGgg.....",
            "...ggGGGGGgg...",
            ".....Y..ggGY...",
            "..............."),

        "metagross" to hero(
            mapOf('B' to 0x4A6AB8, 'b' to 0x32498A, 'S' to 0xC0C8D0, 's' to 0x808A9A),
            "...............",
            ".S...........S.",
            ".SsBBBBBBBBBsS.",
            ".SBBBBBBBBBBS..",
            "..BBbBBBBbBB...",
            "..BBBbBBbBBB...",
            "..BBBBbbBBBB...",
            "..BBBbBBbBBB...",
            "..BBbBBBBbBB...",
            "..BbBBBBBBbB...",
            "..bBBBBBBBBb...",
            ".Ss.b....b.sS..",
            ".S..b....b..S..",
            ".ss..........s.",
            "..............."),

        "gardevoir" to hero(
            mapOf('W' to 0xF4F2EE, 'w' to 0xC4C4CE, 'G' to 0x48A878, 'g' to 0x2F7A56, 'R' to 0xE04858),
            "....GGGGG......",
            "...GGGGGGG.....",
            "...GGGgGGG.....",
            "...GGgGgGG.....",
            "...GGGgGGG.....",
            "..G..GGG..G....",
            ".....WWW.......",
            "..W..WWW..W....",
            "...W.WWW.W.....",
            "....WWWWW......",
            "...WWWWWWW.....",
            "..WWWwWwWWW....",
            ".WWWwWWWwWWW...",
            ".WwWWWWWWWwW...",
            "..............."),

        "flygon" to hero(
            mapOf('G' to 0x88C858, 'g' to 0x5A9A38, 'R' to 0xD84038, 'd' to 0x3E7028),
            "..g.......g....",
            "...GGGGGGG.....",
            "..GGGGGGGGG....",
            "..GGGGGGGGG....",
            "...GGGGGGG.....",
            "R..gGdGdGg..R..",
            "RR.GGdGdGG.RR..",
            ".RGgGGGGGgGR...",
            ".RGGgGGGgGGR...",
            "..RG.GGG.GR....",
            "....GGGGG......",
            "....gG.Gg......",
            "....g...g.RR...",
            "..........gRR..",
            "..............."),

        "milotic" to hero(
            mapOf('C' to 0xEADCC4, 'c' to 0xC4AE8E, 'R' to 0xC84858, 'r' to 0x8E3040,
                  'B' to 0x5878C8, 'b' to 0x3A5490),
            "....CCC........",
            ".R.CCCCC.R.....",
            ".RRCCCCCRR.....",
            "..RCrCrCR......",
            "....CCC........",
            "....cCC........",
            ".....CCc.......",
            ".....cCC.......",
            "....CCc..br....",
            "...CCC...Bb....",
            "..cCC...BBb....",
            "..CCC..bBBB....",
            "...cCCCBbBb....",
            ".....BB.bB.....",
            "..............."))
}
